version: 2.0

jobs:
  build:
    machine:
      image: circleci/classic:latest
      docker_layer_caching: true
    shell: /bin/bash -l -eo pipefail
    steps:
      - checkout
      - run:
          name: Install dependencies via npm
          command: npm install
      - run:
          name: Start docker setup
          command: ./start-development.sh
      - run:
          name: Check formatting & linting
          command: npm run format:check && npm run lint
      - run:
          name: Execute tests
          command: docker exec mailhog-awesome.dev "npm run test"
